repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', '{extends: relaxed, rules: {line-length: {max: 200}}}']
        files: '\.(yaml|yml)$'

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-unit-tests

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: local
    hooks:
      - id: promtool-check
        name: Validate Prometheus config
        entry: docker run --rm -v ${PWD}/monitoring/prometheus:/etc/prometheus prom/prometheus:v2.51.0 promtool check config /etc/prometheus/prometheus.yml
        language: system
        pass_filenames: false
        files: 'monitoring/prometheus/.*\.(yml|yaml)$'

      - id: promtool-rules
        name: Validate Prometheus rules
        entry: docker run --rm -v ${PWD}/monitoring/prometheus:/etc/prometheus prom/prometheus:v2.51.0 promtool check rules /etc/prometheus/rules/*.yml
        language: system
        pass_filenames: false
        files: 'monitoring/prometheus/rules/.*\.(yml|yaml)$'
